using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SideDetectionScript : MonoBehaviour
{
    DiceRollScript diceRollScript;

    void Awake()
    {
        diceRollScript = FindObjectOfType<DiceRollScript>();
    }

    private void OnTriggerStay(Collider sideCollider)
    {
        if (diceRollScript != false)
        {
            if (diceRollScript != null)
            { 
                if (diceRollScript.GetComponent<Rigidbody>().velocity == Vector3.zero)
                {
                    diceRollScript.isLanded = true;
                    diceRollScript.diceFaceNum = sideCollider.name;
                }
                else
                {
                    diceRollScript.isLanded = false;
                }
            }
        }
        else
        {
            Debug.LogError("DicerollScript not found in a scene!");
        }
    }
}